const fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),{session,app}=require('electron');
function createJobs({collectors,store,metrics,loginHealth,onChange=()=>{}}){
 const file=path.join(app.getPath('userData'),'agent-results.json');let latest={};try{latest=JSON.parse(fs.readFileSync(file,'utf8'));for(const j of Object.values(latest))if(j.status==='running'){j.status='interrupted';j.error='上次运行被中断，请重新查询'}}catch{}
 const history=new Map(Object.values(latest).map(j=>[j.id,j]));const controllers=new Map();const copy=x=>JSON.parse(JSON.stringify(x));
 function publish(){onChange(snapshot())}function persist(){fs.writeFileSync(file+'.tmp',JSON.stringify(latest),{mode:0o600});fs.renameSync(file+'.tmp',file)}
 function snapshot(){return copy({jobs:Object.values(latest).sort((a,b)=>b.started_at.localeCompare(a.started_at))})}
 const business={key:'business',title:'经营数据汇总',description:'更新所有店铺的经营数据；抖店优先 Python，拼多多使用后台页面。',columns:[{key:'sales',label:'成交金额',format:'money'},{key:'orders',label:'成交单数'},{key:'shipping',label:'待发货'},{key:'aftersales',label:'待处理售后'},{key:'ad',label:'投放花费',format:'money'}]};
 function list(){const c=collectors.list();return {...c,capabilities:[business,...c.capabilities]}}
 function start(key){const old=latest[key];if(old?.status==='running')return copy(old);if([...controllers].length>=2)throw Error('已有两项查询运行中，请完成后再试');const resolved=key==='business'?null:collectors.resolve(key);const capability=resolved?.capability||business,ctrl=new AbortController(),j={id:randomUUID(),key,title:capability.title,description:capability.description,columns:capability.columns,version:resolved?.module.version,status:'running',completed:0,total:0,stage:'准备登录会话',started_at:new Date().toISOString()};latest[key]=j;history.set(j.id,j);while(history.size>50)history.delete(history.keys().next().value);controllers.set(key,ctrl);persist();publish();
 (async()=>{const startTime=Date.now();try{
  if(key==='business'){metrics.start();let s;do{if(ctrl.signal.aborted)throw Error('查询已取消');s=metrics.snapshot();j.total=s.total;j.completed=s.completed;j.stage='正在更新经营数据';publish();if(s.running)await new Promise(r=>setTimeout(r,500))}while(s.running);j.result={captured_at:s.finishedAt,success:s.summary.included,shop_count:s.total,results:s.shops.map(shop=>{const r=s.results[shop.id];return {shop_id:shop.id,name:shop.name,status:r?.status==='ok'&&r.runId===s.runId?'ok':'error',error:r?.error||'未取得本次数据',...(r?.data?.metrics||{}),captured_at:r?.data?.capturedAt}}),total_seconds:s.durationMs/1000};
  }else{const shops=[];for(const shop of store.items.filter(s=>capability.platforms.includes(s.platform))){if(ctrl.signal.aborted)throw Error('查询已取消');const ses=session.fromPartition('persist:shop-'+shop.id);shops.push({id:shop.id,name:shop.name,cookies:await ses.cookies.get({url:capability.cookieURL}),ua:ses.getUserAgent(),since:(shop.lastScan&&shop.lastScan[capability.id])||null})}j.total=shops.length;j.stage='Python 正在请求平台';publish();j.result=shops.length?await require('./python-worker').call({action:capability.action,shops,dataDir:path.join(app.getPath('userData'),'business-data')},{module:resolved.module,signal:ctrl.signal,group:'agent',timeout:Math.max(30000,Math.ceil(shops.length/3)*180000),onProgress:p=>{j.completed=p.completed;j.stage='Python 正在请求平台';publish()}}):{success:0,shop_count:0,results:[]};if(!Array.isArray(j.result.results))throw Error('模块未返回 results 数组');for(const row of j.result.results){const issue=require('./login-health').errorIssue(row.error);if(issue){loginHealth?.record(row.shop_id,issue,startTime);row.error=require('./login-health').MESSAGES[issue]}else if(row.status==='ok'){loginHealth?.record(row.shop_id,'authenticated',startTime);const sh=store.items.find(x=>x.id===row.shop_id);if(sh){sh.lastScan=Object.assign({},sh.lastScan||{},{[capability.id]:Date.now()})}}}try{store.save()}catch(e){}j.result.total_seconds=(Date.now()-startTime)/1000;j.completed=j.total;}
  if(ctrl.signal.aborted)throw Error('查询已取消');j.status='done';j.stage='查询完成';
 }catch(e){j.status=ctrl.signal.aborted?'cancelled':'error';j.error=e.message;j.stage=j.status==='cancelled'?'已取消':'查询失败';delete j.result}finally{j.finished_at=new Date().toISOString();j.duration_seconds=(Date.now()-startTime)/1000;controllers.delete(key);persist();publish()}})();return copy(j)}
 function get(id){const j=history.get(id);if(!j)throw Error('任务不存在');return copy(j)}
 function cancel(id){const j=get(id);if(j.status!=='running'||latest[j.key]?.id!==id)return j;controllers.get(j.key)?.abort();if(j.key==='business')metrics.cancel();return get(id)}
 function annotate(key,annotations){const j=latest[key];if(!j||!j.result)return snapshot();for(const shop of j.result.results||[])for(const c of shop.candidates||[]){const a=annotations[c.order_id];if(a)Object.assign(c,a)}persist();publish();return snapshot()}
 return {snapshot,list,start,get,cancel,annotate,close(){for(const c of controllers.values())c.abort()}};
}
module.exports={createJobs};
