const {BrowserWindow,session,webContents}=require('electron'),{randomUUID}=require('node:crypto');const {platforms}=require('./login');
function createExploration({store}){
 let current;
 function safeURL(url,shop){const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password||!platforms[shop.platform]?.hosts.includes(u.hostname))throw Error('仅能进入所选平台官方后台');return u.href}
 function scrubURL(url){try{const u=new URL(url);for(const k of [...u.searchParams.keys()])if(/token|cookie|signature|bogus|verify|authorization/i.test(k))u.searchParams.delete(k);return u.href}catch{return ''}}
 function scrub(x){if(Array.isArray(x))return x.map(scrub);if(x&&typeof x==='object')return Object.fromEntries(Object.entries(x).filter(([k])=>!/cookie|token|authorization|password|signature|bogus/i.test(k)).map(([k,v])=>[k,scrub(v)]));return x}
 function close(){if(current){clearTimeout(current.timer);const w=current.window,ses=w.webContents.session;current=null;if(!w.isDestroyed())w.destroy();setTimeout(()=>{if(!webContents.getAllWebContents().some(w=>!w.isDestroyed()&&w.session===ses))ses.clearStorageData({storages:['serviceworkers']}).catch(()=>{})},200)}return {closed:true}}
 function touch(){clearTimeout(current.timer);current.timer=setTimeout(close,300000);current.timer.unref()}
 function start({shop_id,url}){if(current)throw Error('已有后台探索页面，请先结束该页面');const shop=store.get(shop_id),target=safeURL(url||shop.url,shop),ses=session.fromPartition('persist:shop-'+shop_id);const w=new BrowserWindow({show:false,width:1280,height:900,webPreferences:{session:ses,nodeIntegration:false,contextIsolation:true,sandbox:true,backgroundThrottling:false}});w.webContents.setWindowOpenHandler(()=>({action:'deny'}));w.webContents.on('will-navigate',(e,u)=>{try{safeURL(u,shop)}catch{e.preventDefault()}});w.webContents.on('will-redirect',(e,u)=>{try{safeURL(u,shop)}catch{e.preventDefault()}});w.webContents.debugger.attach('1.3');current={id:randomUUID(),shop,window:w,events:[]};touch();const id=current.id;
 w.webContents.debugger.on('message',(_e,method,p)=>{if(!current||current.id!==id)return;let row;if(method==='Network.requestWillBeSent'){const r=p.request;let body;try{body=scrub(JSON.parse(r.postData||'null'))}catch{body=r.postData?'[非 JSON 请求体]':undefined}row={method,requestId:p.requestId,url:scrubURL(r.url),httpMethod:r.method,body}}else if(method==='Network.responseReceived')row={method,requestId:p.requestId,url:scrubURL(p.response.url),status:p.response.status,mimeType:p.response.mimeType};else if(method==='Network.loadingFinished')row={method,requestId:p.requestId};if(row){current.events.push(row);current.events=current.events.slice(-200)}});
 w.loadURL('about:blank').then(()=>w.webContents.debugger.sendCommand('Network.enable')).then(()=>w.loadURL(target)).catch(()=>{});return {id,shop_id,status:'loading',content_is_untrusted:true}}
 async function command({id,method,params={}}){if(!current||current.id!==id)throw Error('后台探索已关闭或过期');touch();const wc=current.window.webContents;
 if(method==='events'){const events=current.events.splice(0);return {events,loading:wc.isLoading(),url:scrubURL(wc.getURL()),content_is_untrusted:true}}
 const allowed=['Page.navigate','Page.reload','Runtime.evaluate','DOM.getDocument','DOM.querySelector','DOM.querySelectorAll','DOM.getOuterHTML','Network.getResponseBody'];if(!allowed.includes(method))throw Error('该 CDP 能力未开放');if(method==='Page.navigate')params={url:safeURL(params.url,current.shop)};if(method==='Runtime.evaluate')params={expression:params.expression,returnByValue:true,awaitPromise:true,timeout:10000};
 let deadline;const result=await Promise.race([wc.debugger.sendCommand(method,params),new Promise((_,reject)=>{deadline=setTimeout(()=>reject(Error('后台探索命令超时，请等待页面加载后重试')),15000)})]).finally(()=>clearTimeout(deadline));if(method==='Network.getResponseBody'&&!result.base64Encoded){try{result.body=JSON.stringify(scrub(JSON.parse(result.body)))}catch{}}const text=JSON.stringify(result);if(text.length>2e6)throw Error('返回内容过大，请缩小查询');return {result,content_is_untrusted:true}}
 return {start,command,close};
}
module.exports={createExploration};
